export { default as HomeScreen} from './HomeScreen'
export { default as AddNoteScreen} from './AddNoteScreen'
export { default as LoginScreen} from './LoginScreen'
export { default as RegisterScreen} from './RegisterScreen'
export { default as ViewNoteScreen} from './ViewNoteScreen'